### ISSUE TITLE
🐛 Bug - <When logging in on the web client, a successful log in will show red error text for a moment before succeeding>

### ISSUE THREAD

**Issue by pnv57** [Vooper-Media-LLC/Valour#113]
**Describe the bug**
When logging in on the web client, a successful log in will show red error text for a moment before succeeding

**To Reproduce**
1. Log in and watch the dialog box carefully

**Expected behavior**
Red error text flashes in the uname/passwd box area quickly before you get taken to the home screen.

**Screenshots**
Too fast for me to get

**System Information:**
 - Valour Platform: Web
     - Browser: Firefox 85.0
     - 
**Additional context**
None.

**Comment by fruitcake5** [comment]
Its not an error, it says `Initialized user successfully!`

Text colour should probably be changed at some point.
