### ISSUE TITLE
Error with panel

### ISSUE THREAD

**Issue by morlanius** [Vooper-Media-LLC/Valour#206]
I opened "create planet" window and closed again in a second panel.
Clicked the close button and the button vanished.
Clicking new panel icon now produces this error.

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Arg_InvalidCastException
System.InvalidCastException: Arg_InvalidCastException
   at Valour.Client.Pages.Index.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
  | (anonymous) | @ | blazor.webassembly.js:1
-- | -- | -- | --
  | (anonymous) | @ | blazor.webassembly.js:1
  | w | @ | blazor.webassembly.js:1
  | _mono_wasm_invoke_js_blazor | @ | dotnet.5.0.2.js:1
  | do_icall | @ | 00aba26a:0x194e58
  | do_icall_wrapper | @ | 00aba26a:0x79df9
  | interp_exec_method | @ | 00aba26a:0x44ad3
  | interp_runtime_invoke | @ | 00aba26a:0x12efff
  | mono_jit_runtime_invoke | @ | 00aba26a:0x118e5f
  | do_runtime_invoke | @ | 00aba26a:0x79d42
  | mono_runtime_invoke_checked | @ | 00aba26a:0xf65d
  | mono_runtime_try_invoke_array | @ | 00aba26a:0x10e831
  | ves_icall_InternalInvoke | @ | 00aba26a:0xed492
  | ves_icall_InternalInvoke_raw | @ | 00aba26a:0xecf57
  | do_icall | @ | 00aba26a:0x194de5
  | do_icall_wrapper | @ | 00aba26a:0x79df9
  | interp_exec_method | @ | 00aba26a:0x44ad3
  | interp_runtime_invoke | @ | 00aba26a:0x12efff
  | mono_jit_runtime_invoke | @ | 00aba26a:0x118e5f
  | do_runtime_invoke | @ | 00aba26a:0x79d42
  | mono_runtime_try_invoke | @ | 00aba26a:0x12982
  | mono_runtime_invoke | @ | 00aba26a:0x10ec2b
  | mono_wasm_invoke_method | @ | 00aba26a:0x108e48
  | (anonymous) | @ | dotnet.5.0.2.js:1
  | call_method | @ | dotnet.5.0.2.js:1
  | (anonymous) | @ | dotnet.5.0.2.js:1
  | beginInvokeDotNetFromJS | @ | blazor.webassembly.js:1
  | h | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | invokeWhenHeapUnlocked | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
'

**Comment by superjacobl** [comment]
@morlanius please use the issue template in the future. What version are you on?

**Comment by Coca16** [comment]
@superjacobl as far as I remember they were directed to make this an issue by Spike (after hard-refreshing) a while ago so this on whatever version was on the 16th

**Comment by morlanius** [comment]
The web version.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by superjacobl** [comment]
Does this still happen?
